# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/dark.css"
locale: en-US
title: "Asvoria K.'s Page"
description: "Asvoria K. is an independent author/artist trying to write stories, <br>and make some digital manga style art with somewhat controversial themes.<br>Thanks for visiting!"
baseurl:
url:
logo: "/images/proudly2.png"
site_icon: "/images/favicon.png"
site_shareimg: "https://asvoria.github.io/Author/images/banner_share.jpeg"
date_format: "%B %-d, %Y"
read_time: false
words_per_minute: 200

# Google Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination
paginate: 2

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: GitHub
    url: https://github.com/Asvoria
    icon: fab fa-github-square
  - title: Youtube Channel
    url: https://www.youtube.com/@badlywritenbyhuman
    icon: fab fa-youtube
  - title: Discord
    url: https://discord.gg/kGF7BVgrU6
    icon: fab fa-discord
  - title: TikTok
    url: https://www.tiktok.com/@asvoria.k
    icon: fab fa-tiktok
